// <auto-generated />
using JewelryShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JewelryShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200425151433_SeedingDb")]
    partial class SeedingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JewelryShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bông tai"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Dây chuyền"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Lắc tay"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Nhẫn"
                        });
                });

            modelBuilder.Entity("JewelryShop.Models.Jewelry", b =>
                {
                    b.Property<int>("JewelryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("JewelryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Jewelries");

                    b.HasData(
                        new
                        {
                            JewelryId = 1,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\284674740971874bd11c5b.jpg",
                            Name = "Bông tai BT001",
                            Price = 356000.0
                        },
                        new
                        {
                            JewelryId = 2,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\28467478017635ffe020fb.jpg",
                            Name = "Bông tai BT002",
                            Price = 750000.0
                        },
                        new
                        {
                            JewelryId = 3,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\42432623515636ae3760fb.jpg",
                            Name = "Bông tai BT003",
                            Price = 600000.0
                        },
                        new
                        {
                            JewelryId = 4,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\4261909584462d336f784b.jpg",
                            Name = "Bông tai BT004",
                            Price = 590000.0
                        },
                        new
                        {
                            JewelryId = 5,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\42619097084234e931c3db.jpg",
                            Name = "Bông tai BT005",
                            Price = 356000.0
                        },
                        new
                        {
                            JewelryId = 6,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\40075270425b22d40c45bb-8c4eef99-91d8-4cc0-aa94-5d6637e088bf.jpg",
                            Name = "Dây chuyền DC001",
                            Price = 520000.0
                        },
                        new
                        {
                            JewelryId = 7,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\40285705182bfd10dd3ecb.jpg",
                            Name = "Dây chuyền DC002",
                            Price = 480000.0
                        },
                        new
                        {
                            JewelryId = 8,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\40285705342b1a0d849cab-e31cfb39-09c2-4caa-bac6-aacea5524a68.jpg",
                            Name = "Dây chuyền DC003",
                            Price = 630000.0
                        },
                        new
                        {
                            JewelryId = 9,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\40330998641f0b71e1ee6b-63f9135b-8f1a-483c-b381-11c7ac1af0ac.jpg",
                            Name = "Dây chuyền DC004",
                            Price = 356000.0
                        },
                        new
                        {
                            JewelryId = 10,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\40331008911b2bc28ef06b.jpg",
                            Name = "Dây chuyền DC005",
                            Price = 356000.0
                        },
                        new
                        {
                            JewelryId = 11,
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25460921337d235c5a2efb.jpg",
                            Name = "Lắc tay LT001",
                            Price = 510000.0
                        },
                        new
                        {
                            JewelryId = 12,
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25460922527c5077094ecb.jpg",
                            Name = "Lắc tay LT002",
                            Price = 800000.0
                        },
                        new
                        {
                            JewelryId = 13,
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25460926987c82da2f76eb-5fb237fb-0459-4c87-a056-04e898681418.jpg",
                            Name = "Lắc tay LT003",
                            Price = 410000.0
                        },
                        new
                        {
                            JewelryId = 14,
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25460927087ded46a2fb3b.jpg",
                            Name = "Lắc tay LT004",
                            Price = 826000.0
                        },
                        new
                        {
                            JewelryId = 15,
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25460927417ee818299d0b-75abee9c-e824-478a-aba8-6ef4b633173a.jpg",
                            Name = "Lắc tay LT005",
                            Price = 690000.0
                        },
                        new
                        {
                            JewelryId = 16,
                            CategoryId = 4,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25460927417ee818299d0b-96e38481-92f5-4490-9e67-fce7bb25a44c.jpg",
                            Name = "Lắc tay LT006",
                            Price = 800000.0
                        },
                        new
                        {
                            JewelryId = 17,
                            CategoryId = 4,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25458755737ce4f80ec48b.jpg",
                            Name = "Nhẫn NH001",
                            Price = 500000.0
                        },
                        new
                        {
                            JewelryId = 18,
                            CategoryId = 4,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25459295557c33d36a66bb.jpg",
                            Name = "Nhẫn NH002",
                            Price = 350000.0
                        },
                        new
                        {
                            JewelryId = 19,
                            CategoryId = 4,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\25459312967ae8ec819bab-9d37d65e-fdbf-44e5-89da-c4e87107f29c.jpg",
                            Name = "Nhẫn NH003",
                            Price = 370000.0
                        },
                        new
                        {
                            JewelryId = 20,
                            CategoryId = 4,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\26458691008bbe214d6bcb.jpg",
                            Name = "Nhẫn NH004",
                            Price = 450000.0
                        },
                        new
                        {
                            JewelryId = 21,
                            CategoryId = 4,
                            Description = "",
                            ImageUrl = "~\\Images\\bongtai\\26458696828af93ff0aa0b.jpg",
                            Name = "Nhẫn NH005",
                            Price = 550000.0
                        });
                });

            modelBuilder.Entity("JewelryShop.Models.Jewelry", b =>
                {
                    b.HasOne("JewelryShop.Models.Category", "Category")
                        .WithMany("Jewelries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
